/**
 * Oil India Limited - Baghewala Field Multi-Well Registry
 * Jodhpur Sandstone Heavy Oil Development, Rajasthan
 * All values declare parameter-level provenance.
 */

import { WellOverview } from "../types/twin";

export const BAGHEWALA_FIELD_WELLS: WellOverview[] = [
  {
    wellId: "BGW-01",
    wellName: "BGW-01",
    field: "BAGHEWALA",
    formation: "JODHPUR SANDSTONE",
    depthMeters: { value: 1025, unit: "m", source: "PUBLISHED_FIELD_REFERENCE", confidencePercent: 98, instrumentOrObserver: "Wireline Depth Log" },
    apiGravity: { value: 17.0, unit: "°API", source: "PUBLISHED_FIELD_REFERENCE", confidencePercent: 95, instrumentOrObserver: "Laboratory Assay" },
    currentCycle: 3,
    currentDay: 14,
    phase: "PRODUCTION",
    status: "HEALTHY",
    bhtCelsius: { value: 118.4, unit: "°C", source: "ESTIMATED", confidencePercent: 94, instrumentOrObserver: "Thermal Observer v0.4" },
    viscosityCp: { value: 410, unit: "cP", source: "ESTIMATED", confidencePercent: 92, instrumentOrObserver: "Andrade Rheology Model" },
    rodFloatingRiskPercent: 14,
    productionBopd: { value: 740, unit: "BOPD", source: "MEASURED", confidencePercent: 97, instrumentOrObserver: "Coriolis Flow Meter" },
    twinConfidencePercent: 94,
    latitude: 27.8124,
    longitude: 72.4182,
  },
  {
    wellId: "BGW-02",
    wellName: "BGW-02",
    field: "BAGHEWALA",
    formation: "JODHPUR SANDSTONE",
    depthMeters: { value: 1045, unit: "m", source: "PUBLISHED_FIELD_REFERENCE", confidencePercent: 98, instrumentOrObserver: "Wireline Depth Log" },
    apiGravity: { value: 16.8, unit: "°API", source: "SCENARIO", confidencePercent: 90, instrumentOrObserver: "Wellhead Sample" },
    currentCycle: 5,
    currentDay: 32,
    phase: "COOLING",
    status: "WARNING",
    bhtCelsius: { value: 58.2, unit: "°C", source: "ESTIMATED", confidencePercent: 88, instrumentOrObserver: "Thermal Observer v0.4" },
    viscosityCp: { value: 7450, unit: "cP", source: "ESTIMATED", confidencePercent: 86, instrumentOrObserver: "Andrade Rheology Model" },
    rodFloatingRiskPercent: 58,
    productionBopd: { value: 410, unit: "BOPD", source: "MEASURED", confidencePercent: 96, instrumentOrObserver: "Coriolis Flow Meter" },
    twinConfidencePercent: 88,
    latitude: 27.8145,
    longitude: 72.4215,
  },
  {
    wellId: "BGW-03",
    wellName: "BGW-03",
    field: "BAGHEWALA",
    formation: "JODHPUR SANDSTONE",
    depthMeters: { value: 1010, unit: "m", source: "PUBLISHED_FIELD_REFERENCE", confidencePercent: 98, instrumentOrObserver: "Wireline Depth Log" },
    apiGravity: { value: 17.5, unit: "°API", source: "SCENARIO", confidencePercent: 92, instrumentOrObserver: "Wellhead Sample" },
    currentCycle: 2,
    currentDay: 4,
    phase: "INJECTION",
    status: "HEALTHY",
    bhtCelsius: { value: 172.0, unit: "°C", source: "ESTIMATED", confidencePercent: 96, instrumentOrObserver: "Thermal Observer v0.4" },
    viscosityCp: { value: 65, unit: "cP", source: "ESTIMATED", confidencePercent: 94, instrumentOrObserver: "Andrade Rheology Model" },
    rodFloatingRiskPercent: 4,
    productionBopd: { value: 0, unit: "BOPD", source: "MEASURED", confidencePercent: 99, instrumentOrObserver: "Coriolis Flow Meter" },
    twinConfidencePercent: 96,
    latitude: 27.8168,
    longitude: 72.4165,
  },
  {
    wellId: "BGW-04",
    wellName: "BGW-04",
    field: "BAGHEWALA",
    formation: "JODHPUR SANDSTONE",
    depthMeters: { value: 1058, unit: "m", source: "PUBLISHED_FIELD_REFERENCE", confidencePercent: 98, instrumentOrObserver: "Wireline Depth Log" },
    apiGravity: { value: 16.5, unit: "°API", source: "SCENARIO", confidencePercent: 89, instrumentOrObserver: "Wellhead Sample" },
    currentCycle: 4,
    currentDay: 39,
    phase: "COOLING",
    status: "CRITICAL",
    bhtCelsius: { value: 44.1, unit: "°C", source: "ESTIMATED", confidencePercent: 82, instrumentOrObserver: "Thermal Observer v0.4" },
    viscosityCp: { value: 14200, unit: "cP", source: "ESTIMATED", confidencePercent: 81, instrumentOrObserver: "Andrade Rheology Model" },
    rodFloatingRiskPercent: 88,
    productionBopd: { value: 185, unit: "BOPD", source: "MEASURED", confidencePercent: 95, instrumentOrObserver: "Coriolis Flow Meter" },
    twinConfidencePercent: 82,
    latitude: 27.8095,
    longitude: 72.4251,
  },
  {
    wellId: "BGW-05",
    wellName: "BGW-05",
    field: "BAGHEWALA",
    formation: "JODHPUR SANDSTONE",
    depthMeters: { value: 1032, unit: "m", source: "PUBLISHED_FIELD_REFERENCE", confidencePercent: 98, instrumentOrObserver: "Wireline Depth Log" },
    apiGravity: { value: 17.1, unit: "°API", source: "SCENARIO", confidencePercent: 91, instrumentOrObserver: "Wellhead Sample" },
    currentCycle: 6,
    currentDay: 8,
    phase: "SOAK",
    status: "HEALTHY",
    bhtCelsius: { value: 189.5, unit: "°C", source: "ESTIMATED", confidencePercent: 95, instrumentOrObserver: "Thermal Observer v0.4" },
    viscosityCp: { value: 52, unit: "cP", source: "ESTIMATED", confidencePercent: 93, instrumentOrObserver: "Andrade Rheology Model" },
    rodFloatingRiskPercent: 6,
    productionBopd: { value: 0, unit: "BOPD", source: "MEASURED", confidencePercent: 99, instrumentOrObserver: "Coriolis Flow Meter" },
    twinConfidencePercent: 95,
    latitude: 27.8182,
    longitude: 72.4289,
  },
  {
    wellId: "BGW-06",
    wellName: "BGW-06",
    field: "BAGHEWALA",
    formation: "JODHPUR SANDSTONE",
    depthMeters: { value: 1038, unit: "m", source: "PUBLISHED_FIELD_REFERENCE", confidencePercent: 98, instrumentOrObserver: "Wireline Depth Log" },
    apiGravity: { value: 17.4, unit: "°API", source: "SCENARIO", confidencePercent: 92, instrumentOrObserver: "Wellhead Sample" },
    currentCycle: 4,
    currentDay: 19,
    phase: "PRODUCTION",
    status: "HEALTHY",
    bhtCelsius: { value: 98.6, unit: "°C", source: "ESTIMATED", confidencePercent: 92, instrumentOrObserver: "Thermal Observer v0.4" },
    viscosityCp: { value: 1120, unit: "cP", source: "ESTIMATED", confidencePercent: 90, instrumentOrObserver: "Andrade Rheology Model" },
    rodFloatingRiskPercent: 22,
    productionBopd: { value: 620, unit: "BOPD", source: "MEASURED", confidencePercent: 97, instrumentOrObserver: "Coriolis Flow Meter" },
    twinConfidencePercent: 92,
    latitude: 27.8111,
    longitude: 72.4132,
  },
  {
    wellId: "BGW-07",
    wellName: "BGW-07",
    field: "BAGHEWALA",
    formation: "JODHPUR SANDSTONE",
    depthMeters: { value: 1048, unit: "m", source: "PUBLISHED_FIELD_REFERENCE", confidencePercent: 98, instrumentOrObserver: "Wireline Depth Log" },
    apiGravity: { value: 16.9, unit: "°API", source: "SCENARIO", confidencePercent: 90, instrumentOrObserver: "Wellhead Sample" },
    currentCycle: 3,
    currentDay: 26,
    phase: "PRODUCTION",
    status: "WARNING",
    bhtCelsius: { value: 71.0, unit: "°C", source: "ESTIMATED", confidencePercent: 89, instrumentOrObserver: "Thermal Observer v0.4" },
    viscosityCp: { value: 6100, unit: "cP", source: "ESTIMATED", confidencePercent: 87, instrumentOrObserver: "Andrade Rheology Model" },
    rodFloatingRiskPercent: 61,
    productionBopd: { value: 490, unit: "BOPD", source: "MEASURED", confidencePercent: 96, instrumentOrObserver: "Coriolis Flow Meter" },
    twinConfidencePercent: 89,
    latitude: 27.8139,
    longitude: 72.4312,
  },
  {
    wellId: "BGW-08",
    wellName: "BGW-08",
    field: "BAGHEWALA",
    formation: "JODHPUR SANDSTONE",
    depthMeters: { value: 1040, unit: "m", source: "PUBLISHED_FIELD_REFERENCE", confidencePercent: 98, instrumentOrObserver: "Wireline Depth Log" },
    apiGravity: { value: 17.2, unit: "°API", source: "PUBLISHED_FIELD_REFERENCE", confidencePercent: 96, instrumentOrObserver: "Laboratory Assay" },
    currentCycle: 4,
    currentDay: 25,
    phase: "PRODUCTION",
    status: "WARNING",
    bhtCelsius: { value: 74.2, unit: "°C", source: "ESTIMATED", confidencePercent: 93, instrumentOrObserver: "Thermal Observer v0.4" },
    viscosityCp: { value: 5820, unit: "cP", source: "ESTIMATED", confidencePercent: 91, instrumentOrObserver: "Andrade Rheology Model" },
    rodFloatingRiskPercent: 64,
    productionBopd: { value: 560, unit: "BOPD", source: "MEASURED", confidencePercent: 97, instrumentOrObserver: "Coriolis Flow Meter" },
    twinConfidencePercent: 93,
    latitude: 27.8155,
    longitude: 72.4201,
  },
  {
    wellId: "BGW-09",
    wellName: "BGW-09",
    field: "BAGHEWALA",
    formation: "JODHPUR SANDSTONE",
    depthMeters: { value: 995, unit: "m", source: "PUBLISHED_FIELD_REFERENCE", confidencePercent: 98, instrumentOrObserver: "Wireline Depth Log" },
    apiGravity: { value: 17.8, unit: "°API", source: "SCENARIO", confidencePercent: 93, instrumentOrObserver: "Wellhead Sample" },
    currentCycle: 1,
    currentDay: 11,
    phase: "PRODUCTION",
    status: "HEALTHY",
    bhtCelsius: { value: 145.0, unit: "°C", source: "ESTIMATED", confidencePercent: 95, instrumentOrObserver: "Thermal Observer v0.4" },
    viscosityCp: { value: 180, unit: "cP", source: "ESTIMATED", confidencePercent: 93, instrumentOrObserver: "Andrade Rheology Model" },
    rodFloatingRiskPercent: 9,
    productionBopd: { value: 810, unit: "BOPD", source: "MEASURED", confidencePercent: 98, instrumentOrObserver: "Coriolis Flow Meter" },
    twinConfidencePercent: 95,
    latitude: 27.8078,
    longitude: 72.4174,
  },
  {
    wellId: "BGW-10",
    wellName: "BGW-10",
    field: "BAGHEWALA",
    formation: "JODHPUR SANDSTONE",
    depthMeters: { value: 1060, unit: "m", source: "PUBLISHED_FIELD_REFERENCE", confidencePercent: 98, instrumentOrObserver: "Wireline Depth Log" },
    apiGravity: { value: 16.4, unit: "°API", source: "SCENARIO", confidencePercent: 88, instrumentOrObserver: "Wellhead Sample" },
    currentCycle: 5,
    currentDay: 43,
    phase: "CYCLE_END",
    status: "CRITICAL",
    bhtCelsius: { value: 38.2, unit: "°C", source: "ESTIMATED", confidencePercent: 81, instrumentOrObserver: "Thermal Observer v0.4" },
    viscosityCp: { value: 16800, unit: "cP", source: "ESTIMATED", confidencePercent: 80, instrumentOrObserver: "Andrade Rheology Model" },
    rodFloatingRiskPercent: 94,
    productionBopd: { value: 65, unit: "BOPD", source: "MEASURED", confidencePercent: 94, instrumentOrObserver: "Coriolis Flow Meter" },
    twinConfidencePercent: 81,
    latitude: 27.8201,
    longitude: 72.4234,
  },
  {
    wellId: "BGW-11",
    wellName: "BGW-11",
    field: "BAGHEWALA",
    formation: "JODHPUR SANDSTONE",
    depthMeters: { value: 1030, unit: "m", source: "PUBLISHED_FIELD_REFERENCE", confidencePercent: 98, instrumentOrObserver: "Wireline Depth Log" },
    apiGravity: { value: 17.3, unit: "°API", source: "SCENARIO", confidencePercent: 91, instrumentOrObserver: "Wellhead Sample" },
    currentCycle: 2,
    currentDay: 18,
    phase: "PRODUCTION",
    status: "HEALTHY",
    bhtCelsius: { value: 104.2, unit: "°C", source: "ESTIMATED", confidencePercent: 91, instrumentOrObserver: "Thermal Observer v0.4" },
    viscosityCp: { value: 850, unit: "cP", source: "ESTIMATED", confidencePercent: 89, instrumentOrObserver: "Andrade Rheology Model" },
    rodFloatingRiskPercent: 19,
    productionBopd: { value: 670, unit: "BOPD", source: "MEASURED", confidencePercent: 97, instrumentOrObserver: "Coriolis Flow Meter" },
    twinConfidencePercent: 91,
    latitude: 27.8166,
    longitude: 72.4345,
  },
  {
    wellId: "BGW-12",
    wellName: "BGW-12",
    field: "BAGHEWALA",
    formation: "JODHPUR SANDSTONE",
    depthMeters: { value: 1052, unit: "m", source: "PUBLISHED_FIELD_REFERENCE", confidencePercent: 98, instrumentOrObserver: "Wireline Depth Log" },
    apiGravity: { value: 16.7, unit: "°API", source: "SCENARIO", confidencePercent: 89, instrumentOrObserver: "Wellhead Sample" },
    currentCycle: 4,
    currentDay: 29,
    phase: "COOLING",
    status: "WARNING",
    bhtCelsius: { value: 66.8, unit: "°C", source: "ESTIMATED", confidencePercent: 87, instrumentOrObserver: "Thermal Observer v0.4" },
    viscosityCp: { value: 6800, unit: "cP", source: "ESTIMATED", confidencePercent: 85, instrumentOrObserver: "Andrade Rheology Model" },
    rodFloatingRiskPercent: 67,
    productionBopd: { value: 440, unit: "BOPD", source: "MEASURED", confidencePercent: 96, instrumentOrObserver: "Coriolis Flow Meter" },
    twinConfidencePercent: 87,
    latitude: 27.8089,
    longitude: 72.4287,
  },
];
